config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#cv1'

  get 'ats' => 'vacancy_template#ats_template'

  get 'cv1' => 'static_pages#cv1'

  get 'cv2' => 'static_pages#cv2'

  get 'cv3' => 'static_pages#cv3'

  get 'personal_statement' => 'static_pages#personal_statement'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	  layout 'govuk_template'
  def cv1
  end

  def cv2
  end

  def cv3
  end

  def personal_statement
  end
end

app/controllers/vacancy_template_controller.rb
class VacancyTemplateController < ApplicationController
  def ats_template
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vacancy_template_helper.rb
module VacancyTemplateHelper
end

app/views/layouts/_cv_content.html.erb
<h1 class="heading-large">Your CV</h1>

<p>Your CV is a summary of your employment history, qualifications and skills.</p>

<p>Don’t include any personal information that could identify you.</p>

<p>This will help us recruit based on your knowledge and skills and not your background, gender and ethnicity. Further information is available on <%= link_to "GOV.UK", "https://civilservice.blog.gov.uk/2015/12/01/name-blind-recruitment-responding-to-your-comments/"%>.</p>
<div id="personal-details">
<p>Remove any reference to your:</p>

<ul class="list list-bullet">
	<li>name or title</li>
	<li>age or gender</li>
	<li>email address</li>
	<li>postal address or telephone number</li>
	<li>nationality or immigration status</li>
</ul>
</div>

app/views/layouts/_pers_content.html.erb
<p>Use your personal statement to explain why you’re right for the job.</p>

<p>Don’t include any personal information that could identify you.</p>

<p>This will help us ensure fairness when your application is reviewed and help us build a more diverse, inclusive workforce. Further information is available on <%= link_to "GOV.UK", "https://civilservice.blog.gov.uk/2015/12/01/name-blind-recruitment-responding-to-your-comments/"%>.</p>

<p>Remove any reference to your:</p>
<div id="personal-details">
<ul class="list list-bullet">
	<li>name or title</li>
	<li>age or gender</li>
	<li>email address</li>
	<li>postal address or telephone number</li>
	<li>nationality or immigration status</li>
</ul>
</div>

app/views/layouts/_progress_tracker.html.erb
<div class="column-one-third">
		<ul class="prog-tracker">
			<li><%= link_to "Eligibility checker", '#' %></li>
			<li><%= link_to "Your details", '#' %></li>
			<li class="prog-item--active"><%= link_to "Your CV",   cv1_path %></li>
			<li><%= link_to "Personal statement",   personal_statement_path %></li>
			<li><%= link_to "Diversity and inclusion", '#' %></li>
			<li><%= link_to "Additional requirements", '#' %></li>
		</ul>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ATS - Vacancy template design</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/cv1.html.erb
<% content_for :page_title do %>
Civil Service Jobs - CV Option 1 - GOV.UK
<% end %>
<% content_for :head do %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<% end %>
<% content_for :inside_header do%>
<div class='header-proposition'>
  <div class='content'>
    <nav id='proposition-menu'>
      <a href='/' id='proposition-name'>Civil Service Jobs</a>
    </nav>
  </div>
</div>
<% end %>

<div id="content">
<div id="page-container">

	<div class="phase-banner">
	  <p>
	    <strong class="phase-tag">ALPHA</strong>
	    <span>This is a prototype – your <%= mail_to "support.csjobs@csresourcing.gsi.gov.uk" , "feedback" %> will help us to improve it.</span>
	  </p>
	</div>

	<div class="grid-row">

		<%= render 'layouts/progress_tracker' %>

		<div class="column-two-thirds">
		<%= render 'layouts/cv_content' %>
		<form>
		<fieldset>
		<legend>CV details</legend>
		<div class="form-group">
		<label class="form-label" for="full-name-f1">Employment history<span class="help-text">Enter your full history starting with the most recent</span></label>
  		<textarea class="form-textarea" name="career-history" id="full-name-f1" rows="20" cols="40"></textarea>
  		</div>
  		<div class="form-group">
		<label class="form-label" for="full-name-f1">Qualification details<span class="help-text">Enter your educational and professional qualifications</span></label>
  		<textarea class="form-textarea" name="qualifications" id="full-name-f1" rows="20" cols="40"></textarea>
  		</div>
  		<div class="form-group">
			<label class="block-label" for="waste-type-1">
	        <input id="waste-type-1" name="waste-types" type="checkbox" value="waste-animal">
	        I have removed <%= link_to "personal information", "#personal-details"%> that could identify me
	    	</label>
		</div>
  		</fieldset>
  		</form>
  		<div class="form-group">
		<%= link_to "Save and continue",   personal_statement_path, class: "button" %>
		</div>
		</div>

	</div>
</div>
</div>

app/views/static_pages/cv2.html.erb
<% content_for :page_title do %>
Civil Service Jobs - CV Option 2 - GOV.UK
<% end %>
<% content_for :head do %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<% end %>
<% content_for :inside_header do%>
<div class='header-proposition'>
  <div class='content'>
    <nav id='proposition-menu'>
      <a href='/' id='proposition-name'>Civil Service Jobs</a>
    </nav>
  </div>
</div>
<% end %>

<div id="content">
<div id="page-container">

	<div class="phase-banner">
	  <p>
	    <strong class="phase-tag">ALPHA</strong>
	    <span>This is a prototype – your <%= mail_to "support.csjobs@csresourcing.gsi.gov.uk" , "feedback" %> will help us to improve it.</span>
	  </p>
	</div>

	<div class="grid-row">

		<%= render 'layouts/progress_tracker' %>

		<div class="column-two-thirds">
		<%= render 'layouts/cv_content' %>
		<form>
		<fieldset>
		<legend>CV details</legend>
		<div class="form-group">
		<label class="form-label" for="full-name-f1">Add your CV</label>
  		<textarea class="form-textarea" id="full-name-f1" rows="40" cols="72"></textarea>
  		</div>
  		</fieldset>
  		</form>
  		<div class="form-group">
		<%= link_to "Save and continue",   personal_statement_path, class: "button" %>
		</div>
		</div>

	</div>
</div>
</div>

app/views/static_pages/cv3.html.erb
<% content_for :page_title do %>
Civil Service Jobs - CV Option 3 - GOV.UK
<% end %>
<% content_for :head do %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<% end %>
<% content_for :inside_header do%>
<div class='header-proposition'>
  <div class='content'>
    <nav id='proposition-menu'>
      <a href='/' id='proposition-name'>Civil Service Jobs</a>
    </nav>
  </div>
</div>
<% end %>

<div id="content">
<div id="page-container">

	<div class="phase-banner">
	  <p>
	    <strong class="phase-tag">ALPHA</strong>
	    <span>This is a prototype – your <%= mail_to "support.csjobs@csresourcing.gsi.gov.uk" , "feedback" %> will help us to improve it.</span>
	  </p>
	</div>

	<div class="grid-row">

		<%= render 'layouts/progress_tracker' %>

		<div class="column-two-thirds">
		<%= render 'layouts/cv_content' %>
		<form>
		<fieldset>
		<legend>CV details</legend>
		<div class="form-group">
		<label class="form-label" for="full-name-f1">Skills<span class="help-text">Enter skills relevant to the advertised job</span></label>
  		<textarea class="form-textarea" id="full-name-f1" rows="20" cols="40"></textarea>
  		</div>
  		<div class="form-group">
		<label class="form-label" for="full-name-f1">Employment history<span class="help-text">Enter your full history starting with the most recent</span></label>
  		<textarea class="form-textarea" id="full-name-f1" rows="20" cols="40"></textarea>
  		</div>
  		<div class="form-group">
		<label class="form-label" for="full-name-f1">Qualification details<span class="help-text">Enter your educational and professional qualifications</span></label>
  		<textarea class="form-textarea" id="full-name-f1" rows="20" cols="40"></textarea>
  		</div>
  		<div class="form-group">
			<label class="block-label" for="waste-type-1">
	        <input id="waste-type-1" name="waste-types" type="checkbox" value="waste-animal">
	        I have removed <%= link_to "personal information", "#personal-details"%> that could identify me
	    	</label>
		</div>
  		</fieldset>
  		</form>
  		<div class="form-group">
		<%= link_to "Save and continue",   personal_statement_path, class: "button" %>
		</div>
		</div>

	</div>
</div>
</div>

app/views/static_pages/personal_statement.html.erb
<% content_for :page_title do %>
Civil Service Jobs - Personal statement - GOV.UK
<% end %>
<% content_for :head do %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<% end %>
<% content_for :inside_header do%>
<div class='header-proposition'>
  <div class='content'>
    <nav id='proposition-menu'>
      <a href='/' id='proposition-name'>Civil Service Jobs</a>
    </nav>
  </div>
</div>
<% end %>

<div id="content">
<div id="page-container">

	<div class="phase-banner">
	  <p>
	    <strong class="phase-tag">ALPHA</strong>
	    <span>This is a prototype – your <%= mail_to "support.csjobs@csresourcing.gsi.gov.uk" , "feedback" %> will help us to improve it.</span>
	  </p>
	</div>

	<div class="grid-row">

		<div class="column-one-third">
		<ul class="prog-tracker">
			<li><%= link_to "Eligibility checker", '#' %></li>
			<li><%= link_to "Your details", '#' %></li>
			<li><%= link_to "Your CV",   cv1_path %></li>
			<li class="prog-item--active"><%= link_to "Personal statement",   personal_statement_path %></li>
			<li><%= link_to "Diversity and inclusion", '#' %></li>
			<li><%= link_to "Additional requirements", '#' %></li>
		</ul>
		</div>

		<div class="column-two-thirds">
		<h1 class="heading-large">Personal statement</h1>
		<%= render 'layouts/pers_content'%>
			<form>
				<fieldset>
					<legend>Personal statement</legend>
				<div class="form-group">
					<label class="form-label" for="full-name-f1">Enter your statement<span class="help-text">For example, give your reasons for wanting the job, your most relevant skills and any transferable skills you have.<br>Not to exceed 800 words</span></label>
			  		<textarea class="form-textarea" name="pers-statement" id="word_count" rows="50" cols="72"></textarea>
					<p class="margin_top">Word count <span class="word-counter count__pers-statement" id="display_count">0</span></p>
			  	</div>
			  	<div class="form-group">
					<label class="block-label" for="waste-type-1">
			        <input id="waste-type-1" name="waste-types" type="checkbox" value="waste-animal">
			        I have removed personal information that could identify me
			    	</label>
				</div>
		  		</fieldset>
	  		</form>
	  		<div class="form-group">
		<%= link_to "Save and continue",   personal_statement_path, class: "button" %>
		</div>
		</div>

	</div>
</div>
</div>
<script type="text/javascript">
	$(document).ready(function () {
	var max_count = 800;
    var wordCounts = {};
    
     $("#word_count").on('keyup', function() {
        var words = this.value.match(/\S+/g).length;
        if (words > max_count) {
            // Split the string on first 200 words and rejoin on spaces
            var trimmed = $(this).val().split(/\s+/, max_count).join(" ");
            // Add a space at the end to keep new typing making new words
            $(this).val(trimmed + " ");
        }
        else {
            $('#display_count').html(words);
        }
    });
    
    
    }).keyup();
</script>

app/views/vacancy_template/ats_template.html.erb
<div id="content">
<div id="page-container">
<div div class="grid-row">
<h1 class="heading-large">Vacancy template</h1>
<div class="column-one-half">
	<h2 class="heading-medium">Form input</h2>
	
		<form>
			<fieldset>
				<legend>Application setup</legend>
		<div class="form-set">
				Name blind recruitment (hidden from vacancy holders)<br>
			<input id="not-select-blind" type="radio" name="blind-sift" value="Not selected"><label for="not-select-blind">Not selected</label>
			<input id="yes-select-blind" type="radio" name="blind-sift" value="Yes" checked><label for="yes-select-blind">Yes</label>
			<input id="no-select-blind" type="radio" name="blind-sift" value="No"><label for="no-select-blind">No</label>
		</div>
		<div class="form-set old current">
				Upload CV (current)<br>
			<input id="not-select-cv" type="radio" name="CV-upload" value="Not selected" checked><label for="not-select-cv">Not selected</label>
			<input id="yes-select-cv" type="radio" name="CV-upload" value="Yes"><label for="yes-select-cv">Yes</label>
			<input id="no-select-cv" type="radio" name="CV-upload" value="No"><label for="no-select-cv">No</label>
		</div>
		<div class="form-set current">
				Upload additional attachment (current)<br>
			<input id="not-select-supporting" type="radio" name="supporting-upload" value="Not selected" checked><label for="not-select-supporting">Not selected</label>
			<input id="yes-select-supporting" type="radio" name="supporting-upload" value="Yes"><label for="yes-select-supporting">Yes</label>
			<input id="no-select-supporting" type="radio" name="supporting-upload" value="No"><label for="no-select-supporting">No</label>
		</div>
		<div id="support-statement" class="form-set enter-details">
			<label for="supporting-doc">Enter details (current)</label>
			<textarea name="enter-details" id="supporting-doc"></textarea>
		</div>

		<div class="form-set new">
			Ask for CV details (new)<br>
			<input id="not-select-cv-upload" type="radio" name="CV-new" value="Not selected" checked><label for="not-select-cv-upload">Not selected</label>
			<input id="yes-select-cv-upload" type="radio" name="CV-new" value="Yes"><label for="yes-select-cv-upload">Yes</label>
			<input id="no-select-cv-upload" type="radio" name="CV-new" value="No"><label for="no-select-cv-upload">No</label>
		</div>
		<div class="form-set skills-optional">
			Include a section for skills (new)<br>
			<input id="not-select-skills" type="radio" name="skills-new" value="Not selected" checked><label for="not-select-skills">Not selected</label>
			<input id="yes-select-skills" type="radio" name="skills-new" value="Yes"><label for="yes-select-skills">Yes</label>
			<input id="no-select-skills" type="radio" name="skills-new" value="No"><label for="no-select-skills">No</label>
		</div>
		<div class="form-set new">
			Ask for a Personal statement (new)<br>
			<input id="not-select-personal" type="radio" name="personal-new" value="Not selected" checked><label for="not-select-personal">Not selected</label>
			<input id="yes-select-personal" type="radio" name="personal-new" value="Yes"><label for="yes-select-personal">Yes</label>
			<input id="no-select-personal" type="radio" name="personal-new" value="No"><label for="no-select-personal">No</label>
		</div>

			</fieldset>
		</form>
</div>
<div class="column-one-half">
	<h2 class="heading-medium">Output scenarios</h2>
	<p>If name blind recruitment is yes or not selected:</p>
	<ul class="list list-bullet">
		<li class="blind-yes">anonymise application form</li>
		<li class="blind-yes">ask new CV/Personal statement questions</li>
		<li class="blind-yes">hide existing CV questions</li>
	</ul>
	<p>If new ask for CV question is yes:</p>
	<ul class="list list-bullet">
		<li class="cv-yes">add new CV section to app form</li>
		<li class="cv-yes">remove 'Job history' section</li>
		<li class="cv-yes">ask new do you want skills question</li>
	</ul>
	<p>If include a section on skills is yes:</p>
	<ul class="list list-bullet">
		<li class="skills-yes">add skills to new CV section</li>
	</ul>
	<p>If ask for a personal statement is yes:</p>
	<ul class="list list-bullet">
		<li class="statement-yes">add new personal statement section to app form</li>
	</ul>
	<p>If name blind recruitment is no:</p>
	<ul class="list list-bullet">
		<li class="blind-no">override anonymity</li>
		<li class="blind-no">ask existing CV questions</li>
	</ul>
	<p>If existing CV question is yes:</p>
	<ul class="list list-bullet">
		<li class="old-cv-yes">remove 'Job history' section</li>
		<li class="old-cv-yes">add existing CV upload section to app form</li>
	</ul>
</div>
<div class="column-two-thirds">
	<h2 class="heading-medium">Acceptance criteria</h2>
	<h3 class="heading-small">Sprint #28 (must)</h3>
	<p>Story 1 - add name blind sift question to replace override anonymity question:</p>
	<ul class="list list-bullet">
		<li>replace existing override anonymisation question with 'Name blind recruitment' question</li>
		<ul class="list list-bullet">
			<li>position new question above existing CV question on the main create vacancy form</li>
			<li>disable and hide field if user is a vacancy holder</li>
			<li>default value to 'yes' for all departments via job family templates</li>
			<li>users with recuiter, retained team and system administrator roles can see and edit value</li>
			<li>if value is yes existing anonymity functionality is enforced. No overrides existing anonymisation.</li>
		</ul>
	</ul>
	<p>Story 2 - set dependencies and introduce new input fields to trigger new sections</p>
	<ul class="list list-bullet">
		<li>add three new questions below existing supporting document (aka. additional attachment) details field</li>
		<ul class="list list-bullet">
			<li>all fields will be yes/no radio input fields</li>
			<li>first input label will be: "Ask for CV details"</li>
			<li>second input label will be: "Include a section for skills"</li>
			<li>third input label will be: "Ask for a personal statement"</li>
		</ul>
		<li>if name blind sift is 'yes' or 'not selected' show the new fields and hide the existing CV field</li>
		<li>if name blind sift is 'no' hide the new fields and show the existing CV field</li>
	</ul>
	<p>Story 3 - hide job history section going forward if CV (upload or form versions) are asked for</p>
	<ul class="list list-bullet">
		<li>going forward, remove the job history section if a CV is asked for</li>
		<li>when reviewing legacy vacancies that asked for a CV, job history information should be apparent</li>
	</ul>
	<h3 class="heading-small">Sprint #29 (must)</h3>
	<p>Story 4 - Introduce a new section 'Your CV'</p>
	<ul class="list list-bullet">
		<li>TBC</li>
	</ul>
	<p>Story 4 - Introduce a new section 'Personal statement'</p>
	<ul class="list list-bullet">
		<li>TBC</li>
	</ul>
</div>
</div>
</div>
</div>